[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_crowdfunding = "7s9rxZqqDKkcn2QPvhBszuxEwiR7CPL4sLNdxiQpCKEJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
